import re
import ast
from typing import Dict
from .exceptions import ParseException, IllegalMoveException

# =================================================
# General Functionality
# =================================================
def extract_solution(text: str) -> str:
    """ Extracts text between <answer> and </answer> tags, trims it, and returns it. """
    matches = re.findall(r"<answer>(.*?)</answer>", text, re.DOTALL)
    if not matches:
        raise ParseException("No valid pair of <answer> tags found.")
    extracted = matches[-1].strip()
    return extracted


def coerce_response(text: str, task_type: str) -> str:
    """ Given an output generated by an LLM, coerces it to be in a more workable format. """
    try:
        processed_text = ast.literal_eval(text)
    except:
        processed_text = text

    # Need output to be a single string (no list)
    if task_type == 'choose_from_n' or task_type == 'predict_singlemove' or task_type == 'predict_in_list':
        if isinstance(processed_text, str):
            processed_text = _stringify_move(processed_text)
        elif isinstance(processed_text, list):
            if len(processed_text) == 1:
                processed_text = _stringify_move(processed_text[0])
            elif len(processed_text) > 1:
                raise ParseException("Output is a list with multiple elements.")
        else:
            raise ParseException("Output is not in the correct format.") 
    
    # Need to coerce to a list of strings
    elif task_type == 'produce_list':
        if isinstance(processed_text, list):
            # Process each element to ensure all elements are strings
            processed_text = [_stringify_move(x) for x in processed_text]
        elif isinstance(processed_text, str):
            processed_text = re.split(r'[\s,]+', processed_text.strip()) if processed_text.strip() else []
            processed_text = _coerce_string_list(processed_text)
        else:
            raise ParseException("Output is not a list.")
    
    # Need to coerce a list of tuples (position / move, piece)
    elif task_type == "hallucination":
        pass

    # Need to coerce list into a dict of key: bool
    elif task_type == "reasoning_strategy":
        extracted = extract_solution(text)
        return _coerce_dict_bool(extracted)

    else:
        raise ValueError(f"Unknown eval type: {task_type}")
    
    return processed_text


# ==================================================
# Helper Functions
# ==================================================
def _stringify_move(move: str) -> str:
    return ''.join(c for c in move if c.isalnum())    

def _coerce_string_list(items: list[str]) -> list[str]:
    pattern = re.compile(r'^[a-zA-Z]\d(?:[a-zA-Z]\d)?$')
    filtered = [item for item in items if pattern.match(item)]
    
    if not filtered:
        raise ParseException("No valid items found in input.")
    
    return filtered

def _coerce_dict_bool(items: str) -> Dict[str, int]:
    allowed_keys = {'backtrack', 'verification', 'enumeration', 'subgoal setting'}

    # First try to parse into a dict
    try:
        parsed = ast.literal_eval(items)
    except Exception as e:
        raise ParseException(f"Failed to parse input as a dictionary: {e}")
    if not isinstance(parsed, dict):
        raise ParseException("Parsed input is not a dictionary.")

    errors = []
    result = {}
    # Now ensure valid keys / values
    for key, value in parsed.items():
        if key not in allowed_keys:
            errors.append(f"Invalid key: '{key}' (allowed: {sorted(allowed_keys)})")
        if value not in ('0', '1'):
            errors.append(f"Invalid value for key '{key}': '{value}' (must be '0' or '1')")
        if key in allowed_keys and value in ('0', '1'):
            result[key] = int(value)

    if errors:
        raise ParseException("Errors in input:\n" + "\n".join(errors))

    return result


# ==================================================
# LLM Parser Helpers
# ==================================================
def _coerce_hallucinations():
    raise NotImplementedError()