### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: ds_config_zero2
push_to_hub: true

### dataset
dataset: llmchess_programmatic
template: none
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: sft-model
logging_steps: 1
save_steps: 7500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

evaluation_strategy: "no"

### reporting
report_to: wandb
run_name: llama3-8b-sft-llmchess-programmatic