### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: ./ds_z3_config.json
push_to_hub: false

### dataset
dataset: llmchess_programmatic
template: none
cutoff_len: 4096
overwrite_cache: true

### output
output_dir: ./sft-model
logging_steps: 10
save_strategy: epoch
save_total_limit: 1
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
lr_scheduler_type: cosine
warmup_ratio: 0.1
num_train_epochs: 1.0
bf16: true
ddp_timeout: 180000000

### reporting
report_to: wandb
wandb_project: llm-chess-sft
wandb_entity: lucasdino-ucsd